---
- name: Deploy WiFi Trust‐Testing Agent
  hosts: trust-node-01
  become: yes
  vars:
    trust_agent_dir: /opt/trust-agent
  tasks:

    - name: Ensure system packages for WiFi scanning
      package:
        name:
          - python3-pip
          - wireless-tools
          - aircrack-ng
          - iw
        state: present

    - name: Create agent directory
      file:
        path: "{{ trust_agent_dir }}"
        state: directory
        owner: co-admin
        group: co-admin
        mode: "0755"

    - name: Copy Python trust‐test script and config
      copy:
        src: 
          - scripts/trust_test_node.py
          - scripts/trust_config.yaml
        dest: "{{ trust_agent_dir }}/"
        owner: co-admin
        group: co-admin
        mode: "0755"

    - name: Install Python dependencies
      pip:
        name:
          - scapy
          - pyyaml
        executable: pip3

    - name: Deploy systemd unit for trust‐test agent
      copy:
        dest: /etc/systemd/system/trust-test-node.service
        content: |
          [Unit]
          Description=WiFi Trust‐Testing Agent
          After=network.target

          [Service]
          User=co-admin
          Group=co-admin
          WorkingDirectory={{ trust_agent_dir }}
          ExecStart=/usr/bin/python3 {{ trust_agent_dir }}/trust_test_node.py
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd & enable agent
      systemd:
        daemon_reload: yes
        name: trust-test-node.service
        enabled: yes
        state: started