name: Verify Supply‐Chain Provenance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-supply-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Echo test
        run: echo "✅ Workflow initialized"